spring:
  data:
    mongodb:
      auto-index-creation: true
      database: urlsolution
      authentication-database: urlsolution
      host: <ip>>
      port: 27017
      username: root
      password: <pwd>
  datasource:
    url: ${RDS_JDBC_URL:jdbc:postgresql://<ip>>:5432/mydb}
    username: ${RDS_USERNAME:ankur}
    password: ${RDS_PASSWORD:<pwd>>}
    platform: postgres
    driverClassName: org.postgresql.Driver
    hikari:
      idle-timeout: 60000
      maximum-pool-size: 150
      minimum-idle: 5
      schema: myapp
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        query:
          plan_cache_max_size: 1
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        use_sql_comments: false
        format_sql: false
